### ISSUE TITLE
Create a guide that lets someone deploy the test-lab master (for now just Kubernetes master)

### ISSUE THREAD

**Issue by jbenet** [ipfs/test-lab#17]
Create a guide that lets someone deploy the test-lab master (for now just Kubernetes master)

**Deliverable:** a markdown file in this repo that someone can rely on to deploy the test-lab master. We will try it out next week.

Notes:
- The guide could make use of other guides, but the more self-contained it is, the better.

**Comment by jbenet** [comment]
We still need this guide. When can you write it @FrankPetrilli ?

**Comment by jbenet** [comment]
https://github.com/ipfs/test-lab/tree/master/guides

**Comment by FrankPetrilli** [comment]
https://github.com/ipfs/test-lab/blob/master/guides/deploying-the-orchestrator.md
