### ISSUE TITLE
Create a guide that lets someone setup a lablet

### ISSUE THREAD

**Issue by jbenet** [ipfs/test-lab#18]
Create a guide that lets someone setup a lablet and connect it to the test-lab master. 

**Deliverable:** a markdown file in this repo, and all the assets it references (VM, etc).

Other notes:
- It should cover installation through a VM or natively separately (two sections).
- It should cover installation to Linux
- It may cover installation to macOS

**Comment by FrankPetrilli** [comment]
OVA template is ready to distribute, I'll have a guide for native deployments.

**Comment by jbenet** [comment]
We still need this guide. when could you have it done @FrankPetrilli ?

**Comment by jbenet** [comment]
https://github.com/ipfs/test-lab/tree/master/guides

**Comment by FrankPetrilli** [comment]
https://github.com/ipfs/test-lab/blob/master/guides/setting-up-lablet.md

OVA is coming when I get some RAM available on the host to move things around later tonight.
