### ISSUE TITLE
Create a guide for issuing jobs to the test-lab

### ISSUE THREAD

**Issue by jbenet** [ipfs/test-lab#19]
Create a guide for issuing jobs to the test-lab.

**Deliverable:** a markdown file in this repo.

Other notes:
- it should have a real example using go-ipfs and two nodes (eg add then cat) that works.

**Comment by jbenet** [comment]
https://github.com/ipfs/test-lab/tree/master/guides

**Comment by jbenet** [comment]
Who can write this guide?

**Comment by FrankPetrilli** [comment]
https://github.com/ipfs/test-lab/blob/master/guides/issuing-jobs.md
