### ISSUE TITLE
Sprint prep call

### ISSUE THREAD

**Issue by ghost** [ipfs/test-lab#3]
In this call we'll discuss sprint logistics and the general goals and milestones of the sprint. We'll get into the details of who-does-what-and-when on Monday.

Time proposals:
- ~~Thu 23-Feb 18:00 UTC (after PL all hands)~~
- ~~Thu 23-Feb 21:00 UTC~~
- Fri 24-Feb 18:00 UTC (after sprint retrospective)

Let's timebox it to 1 hour duration.

I should have opened this issue right on Monday, sorry.

**Comment by SidHarder** [comment]
@lgierth Should we assign @FrankPetrilli

**Comment by ghost** [comment]
Oh right, invited him

**Comment by whyrusleeping** [comment]
All stated times work for me.

**Comment by Kubuxu** [comment]
I am up for whenever.

**Comment by jbenet** [comment]
I can only do:
- Thu 23-Feb 18:00 UTC (after PL all hands)
- Fri 24-Feb 18:00 UTC (after sprint retrospective)

**Comment by jbenet** [comment]
(important that i be there)

**Comment by victorb** [comment]
Any of the times works for me too.

**Comment by ghost** [comment]
Let's do Fri 24-Feb 18:00 UTC (after sprint retrospective)

**Comment by ghost** [comment]
Sorry about the assignment noise -- UI fail.

**Comment by FrankPetrilli** [comment]
I'm good for the 24th at 18:00UTC.

**Comment by dgrisham** [comment]
Hi --

I've been in communication with @jbenet about IPFS research and am interested in contributing to this sprint. I would likely need more guidance early on as I haven't work with IPFS source before (nor much with Go), but I would be happy to help however I can!

David

**Comment by SidHarder** [comment]
@dgrisham come join us for the sprint prep call at https://zoom.us/j/192655664.

**Comment by dgrisham** [comment]
@SidHarder I had the time wrong and my research meeting overlapped with the call, is there a log of the call I can view?

**Comment by whyrusleeping** [comment]
@dgrisham Yeah, the calls are recorded. @flyingzumwalt will be posting a link to it soon.

**Comment by flyingzumwalt** [comment]
Notes and recording of the IP Test Lab Planning call https://github.com/ipfs/pm/blob/master/meeting-notes/2017-02-24-sprint-planning-interplanetary-test-lab.md

**Comment by dgrisham** [comment]
Awesome, thanks @whyrusleeping  and @flyingzumwalt . Haven't personally worked with any of the tools mentioned (Docker, Jenkins, Kubernetes) so I'm going through intros of those now.
