### ISSUE TITLE
Rename back to InterPlanetary Lab?

### ISSUE THREAD

**Issue by jbenet** [ipfs/test-lab#4]
The original name for this is: 

> InterPlanetary Lab

to hearken back to https://www.planet-lab.org/ -- somewhere along the way this got renamed to InterPlanetary Test Lab. 

- "ipfs / test-lab" or InterPlanetary Test Lab (IPTL) may lose the connection too much.
- i agree "InterPlanetary Lab" is not super clear. (though the people who it counts for may get it fine)
- we could defer and drop the "Test" part when we do computations that are not tests. (though changing names is hard)
- IPL is close to EPFL and JPL, if that counts for anything...

**Comment by SidHarder** [comment]
@jbenet I would be happy to rename this repo.  The sooner the better.  Is this open for debate or a done deal.  Will it be:

InterPlanetary-lab
InterPlanetary-test-lab
interplanetary-test-lab

Should the repo name be all lowercase?

**Comment by gsf** [comment]
If the name returns to InterPlanetary Lab the repo name can be short and sweet at "ipfs/ipl".
