### ISSUE TITLE
Implement and Document the IPTL Orchestrator

### ISSUE THREAD

**Issue by SidHarder** [ipfs/test-lab#6]
Setup a Kubernetes Minikube that can act as the IPTL Orchestrator.  The deliverable here is a document detailing how to setup a Kubernetes Minikube that can be the bases for the IPTL Orhestrator

**Comment by SidHarder** [comment]
@FrankPetrilli Yesterday during the second call we discussed having you and @jonnycrunch work together to document the process of setting up an IPTL Orchestrator using Kubernetes.  I have invited @jonnycrunch to join this repo. Have you been in contact with him?

**Comment by jonnycrunch** [comment]
@FrankPetrilli @SidHarder I've started setting up kubernetes on my cluster and have broken down the action items we discussed into three main deliverables.  1.) Orchestration  2.) Modeling 3.) Dissemination.  At present, I'm interpreting #1 to be just within a local simplified cluster, so I'm starting with minikube, spinning up the appropriate environment (just one flavor of linux for now) and running some code pulled from IPFS to gather some metrics then save the results to IPFS before shutting down the environment.   Give me a couple of days to experiment.  Should we set a time to meet on Friday to discuss over zoom?

**Comment by SidHarder** [comment]
@jonnycrunch I will be getting a standup scheduled soon.  Thanks for your help.

**Comment by jonnycrunch** [comment]
Ok, a couple of notes of what not to do:   

- don't use conjure-up on ubuntu-kubernetes in a production environment using while your network admin is away .  Conjure-up is designed to run using juju and Metal-As-A-Service (MAAS) leveraging ubuntu netboot servers.  This also requires its own dedicated DHCP server for provisioning.  Unfortunately, the conjure up overlay network set up a conflicting DHCP server on the same subnet and I had a bunch of unhappy developers in our colab space.    
- also, I had difficulties running minikube-1.16.0 on ubuntu server 16.04.02 LTR using virtualbox 5.1 in headless mode, but finally got it to run fine on my local mac. version 1.17.1 just came out this morning and i will try it again.  
- We are getting google fiber soon and will be moving my cluster to our own space and will be moving to MAAS.

**Comment by FrankPetrilli** [comment]
See the following, this is the additional needed information to run an IPTL orchestrator which can operate with nodes behind NAT:

https://github.com/ipfs/test-lab/blob/master/guides/deploying-the-orchestrator.md

For just a local installation, use the following:

https://github.com/ipfs/test-lab/blob/master/guides/deploying-a-local-test-lab.md
