### ISSUE TITLE
Experiment with DSL to define and deploy tests on Kubernetes

### ISSUE THREAD

**Issue by SidHarder** [ipfs/test-lab#8]

**Comment by SidHarder** [comment]
@hsanjuan I didn't quite understand what you intend to work on with respect to Kubernetes this week.  Could help me understand better what you plan to do.  I can then modify the issue as appropriate.

**Comment by hsanjuan** [comment]
@SidHarder if I understood correctly, there's a sort of DSL to do testing on Kubernetes and I should use it and see if it is possible to deploy some test (ipfs-cluster test) on the kubernetes thing.

**Comment by SidHarder** [comment]
@hsanjuan I have been poking around a bit with Kubernetes, but its not clear to me if Kubernetes has a DSL.  I see were a few folks have created there own.  Have you found anything?

**Comment by hsanjuan** [comment]
It's something like this @SidHarder :  https://github.com/ipfs/kubernetes-ipfs/blob/master/tests/simple-add-and-cat.yml

**Comment by FrankPetrilli** [comment]
@SidHarder:

Kubernetes has a deployment YAML-based "language". Take a look at https://github.com/ipfs/kubernetes-ipfs/blob/master/go-ipfs-deployment.yml, which creates a 2 container deployment of go-ipfs. You can instantiate this from `kubectl create -f go-ipfs-deployment.yml`.

The test DSL is a result of the kubernetes-ipfs project between Victor and myself, and is custom. Its parsing is defined via the structs in https://github.com/ipfs/kubernetes-ipfs/blob/master/main.go.

**Comment by hsanjuan** [comment]
I'm going to consider this done as I can run ipfs-cluster tests on kubernetes after making some changes to the DSL:

https://github.com/ipfs/kubernetes-ipfs/pull/15

I continue working on #9.
